### ISSUE TITLE
准备入坑机器学习

### ISSUE THREAD

**Issue by dark-wind** [wanghan0501/wanghan0501.github.io#2]
准备入坑机器学习，能不能跟在晗神身边打杂一段时间呢

**Comment by wanghan0501** [comment]
你是？

**Comment by dark-wind** [comment]
今年想考软件智能的研究生，但是不知道是否会真的喜欢这个方向，所以想到实验室来参观学习，了解下日常工作内容和实验室学术氛围。人在附近。。。时间最长能到8月末
